name: Pipe DevSecOps

on:
  workflow_dispatch:
  pull_request: {}
  push:
    branches:
    - main
    - master

permissions:
      contents: read
    
jobs:

#----SAST----#
  semgrep:
    name: SAST-SEMGREP
    runs-on: ubuntu-latest
    permissions:
        contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
    - uses: actions/checkout@v4
    - run: semgrep ci

  sca-snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: src
        run: npm install

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk Test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        working-directory: src
        run: snyk test || true

      - name: Send results to Snyk (monitor)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        working-directory: src
        run: snyk monitor

  dast-zap:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://musical-happiness-pjggq6prxq9vh69q6-3000.app.github.dev/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
