name: Snyk Scan via CLI

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: src
        run: npm install

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk Test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        working-directory: src
        run: snyk test || true

      - name: Send results to Snyk (monitor)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        working-directory: src
        run: snyk monitor
