name: Snyk Example
on: 
  workflow_dispatch:
permissions:
  contents: read
  issues: write
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: snyk/actions/setup@master

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.13"

      - name: Run Snyk Test
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
